version: '3.7'
services:
  nuclio:
    image: quay.io/nuclio/dashboard:stable-amd64
    hostname: nuclio
    ports:
      - 8070:8070
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/tmp:/tmp'